In [1]:
from pymm.models import MarkovModel

import numpy as np

In [25]:
# number of states for categorical variable
K = 2

# order of Markov model
M = 1

generator = MarkovModel(K=K, M=M, random_init=True)

# create artificial dataset
X = [generator.sample(10) for _ in range(1000)]

In [26]:
model = MarkovModel(K=K, M=M)

%timeit -r 1 -n 1 model.fit(X)

C:\Users\AFowl\local\lib\anaconda\envs\pymm\lib\site-packages\scipy-1.7.1-py3.8-win-amd64.egg\scipy\sparse\_index.py:116: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_arrayXarray_sparse(i, j, x)
C:\Users\AFowl\local\lib\anaconda\envs\pymm\lib\site-packages\scipy-1.7.1-py3.8-win-amd64.egg\scipy\optimize\optimize.py:282: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  warnings.warn("Values in x were outside bounds during a "


9.77 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [27]:
model.models[0].A

array([0.62599886, 0.37400114])

In [28]:
generator.models[0].A

array([0.6437402, 0.3562598])

In [29]:
model.models[1].A

array([[0.78300418, 0.17516116],
       [0.21699582, 0.82483884]])

In [30]:
generator.models[1].A

array([[0.793431  , 0.17570343],
       [0.206569  , 0.82429657]])

In [24]:
model.models